### ISSUE TITLE
hello ，大佬。魅族16s 昨晚升级了Flyme 8.0 系统或者是升级了支付宝，因为昨晚一起升级的。现在用最新的1.9.1 版本进入自己首页后报错 ，09:23:56.380/W: 定位"查看更多好友"超时。下面是我回退到1.7.1 收集的错误信息。

### ISSUE THREAD

**Issue by steadyzeus** [SuperMonster003/Auto.js_Projects#101]
09:06:31.740/E: Wrapped android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=alipays://platformapi/startapp?appId=60000002&appClearTop=false&startMultApp=YES flg=0x10000000 } (file:///android_asset/modules/__app__.js#72)
Wrapped android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=alipays://platformapi/startapp?appId=60000002&appClearTop=false&startMultApp=YES flg=0x10000000 }
    at file:///android_asset/modules/__app__.js:72:0
    at launchThisApp (file:/storage/emulated/0/脚本/Auto.js_Projects-master/Modules/MODULE_MONSTER_FUNC.js:212:0)
    at launch (/storage/emulated/0/脚本/Auto.js_Projects-master/Ant_Forest_Launcher.js:1906:0)
    at restartAlipayToHeroList (/storage/emulated/0/脚本/Auto.js_Projects-master/Ant_Forest_Launcher.js:1342:0)
    at backToHeroList (/storage/emulated/0/脚本/Auto.js_Projects-master/Ant_Forest_Launcher.js:1333:0)
    at checkFriendsEnergy (

**Comment by steadyzeus** [comment]
1.9.1 版开启开发者日志截图
![image](https://user-images.githubusercontent.com/16338453/65563172-4bf79900-df7b-11e9-9a4a-047ab564660e.png)

**Comment by steadyzeus** [comment]
1.9.0 ，可以进一次好友列表，然后进入第一个好友的主页偷取后，不能返回好友列表 。开启开发者日志截图 
![image](https://user-images.githubusercontent.com/16338453/65564206-bcec8000-df7e-11e9-82bd-7eec6ba10a4a.png)

**Comment by steadyzeus** [comment]
应该是 最新版本的支付宝 不支持协议打开好友列表页面了 Alipay://....   ，到豌豆荚上找了个v10.1.68.7434 版本安装上，就可以用1.9.1 版本了

**Comment by SuperMonster003** [comment]
感谢反馈 将在下一版尝试修复此问题
