### ISSUE TITLE
在更新1.9.3正常使用一段时间后，突然显示错误

### ISSUE THREAD

**Issue by Geor123** [SuperMonster003/Auto.js_Projects#114]
换手机任然依然没有解决。直接无法运行，连设置功能都打不开，尝试解锁代码可以运行。4.1.1 alpha2版本。

22:14:57.148/E: SyntaxError: JSON.parse (file:///android_asset/modules/__json2__.js#505)
SyntaxError: JSON.parse
    at file:///android_asset/modules/__json2__.js:505:0
    at get (file:/storage/emulated/0/脚本/Auto.js_Projects-master/Modules/MODULE_STORAGE.js:54:0)
    at setInsuranceTaskIfNeeded (/storage/emulated/0/脚本/Auto.js_Projects-master/Ant_Forest_Launcher.js:3851:0)
    at /storage/emulated/0/脚本/Auto.js_Projects-master/Ant_Forest_Launcher.js:71:0

**Comment by SuperMonster003** [comment]
`v1.9.4` 已发布 请尝试更新版本后检查问题是否复现并欢迎再次反馈
