### ISSUE TITLE
华为mate20 pro运行报错

### ISSUE THREAD

**Issue by akatsukily** [SuperMonster003/Auto.js_Projects#128]
Version: 163
Android: 28
org.mozilla.javascript.JavaScriptException: Error: Can't resolve relative module ID "./Modules/__timers__pro_v37" when require() is used outside of a module (<Ant_Forest_Settings>#11)
	at org.mozilla.javascript.ScriptRuntime.throwError(ScriptRuntime.java:4351)
	at org.mozilla.javascript.commonjs.module.Require.call(Require.java:190)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1479)
	at script(<Ant_Forest_Settings>:11)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:399)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3362)
	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:120)
	at org.mozilla.javascript.Context.evaluateReader(Context.java:1266)
	at com.stardust.autojs.engine.RhinoJavaScriptEngine.doExecution(RhinoJavaScriptEngine.java:62)
	at com.stardust.autojs.engine.JavaScriptEngine.execute(JavaScriptEngine.java:21)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.access$001(LoopBasedJavaScriptEngine.java:16)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine$1.run(LoopBasedJavaScriptEngine.java:30)
	at android.os.Handler.handleCallback(Handler.java:891)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:7470)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/127#issuecomment-553263956

**Comment by akatsukily** [comment]
> [第127章（评论）](https://github.com/SuperMonster003/Auto.js_Projects/issues/127#issuecomment-553263956)

可以了，原来是解压的时候多出了一层，谢谢大佬！
