### ISSUE TITLE
偶尔出现收取好友能量出错：cannot call method "bounds" of null

### ISSUE THREAD

**Issue by Johnson-W** [SuperMonster003/Auto.js_Projects#19]
日志显示：
>>点击收取图标
17:10:00.009/E: TypeError: Cannot call method "bounds" of null (/storage/emulated/0/脚本/Tools/!Ant_Forest.js#2340)
TypeError: Cannot call method "bounds" of null
    at /storage/emulated/0/脚本/Tools/!Ant_Forest.js:2340:0
    at clickBounds (/storage/emulated/0/脚本/Tools/!Ant_Forest.js:2349:0)
    at forestPageGetReady (/storage/emulated/0/脚本/Tools/!Ant_Forest.js:886:0)
    at checkFriendsEnergy (/storage/emulated/0/脚本/Tools/!Ant_Forest.js:638:0)
    at checkEnergy (/storage/emulated/0/脚本/Tools/!Ant_Forest.js:501:0)
    at antForest (/storage/emulated/0/脚本/Tools/!Ant_Forest.js:80:0)
    at /storage/emulated/0/脚本/Tools/!Ant_Forest.js:72:0

行数可能不准确，我改了!Ant_Forest.js加了句监视自己能量时屏幕常亮。
具体时这行：
        getPosb = () => func.toString().match(/^Rect\(/) ? func : func.findOnce().bounds();

手机是华为MATE8
auto.js版本4.1.1 Alpha2
脚本是昨天最新更新的

感谢幸苦完善脚本！

**Comment by SuperMonster003** [comment]
clickBounds()方法已更名为clickAction() 内部逻辑已重写 并集成在 `MODULE_GLOBAL_FUNC.js` 模块中  
近期 (不晚于22日) 会发布此模块 当然蚂蚁森林项目中也会使用此模块中的新工具 因此将不再出现空指针问题
