### ISSUE TITLE
Bug反馈: 脚本每天运行几次后，会报错并自动暂停，后续需要重启才能恢复变正常

### ISSUE THREAD

**Issue by PPatrick-GitHub** [SuperMonster003/Auto.js_Projects#259]
**问题描述**
脚本每天运行几次后，会报错并自动暂停，后续需要重启才能恢复变正常

**日志截图**
提供与问题相关的日志截图
![Screenshot_20200224-215607_Autojs](https://user-images.githubusercontent.com/61398202/75158334-d9206300-5750-11ea-9028-49a9c9a0eade.jpg)
![Screenshot_20200224-183541_Autojs](https://user-images.githubusercontent.com/61398202/75158355-e2a9cb00-5750-11ea-9686-40b6771d9ec4.jpg)

**软件硬件信息**
操作系统: 安卓9.0
设备型号: 三星s8+
Auto.js版本: [如: 4.1.1 Alpha2]

**其他**
包括但不限于建议/提案/想法/灵感...

**Comment by PPatrick-GitHub** [comment]
![Screenshot_20200226-235122_Autojs](https://user-images.githubusercontent.com/61398202/75362172-51268e80-58f3-11ea-84d4-fbfa5b1d35f8.jpg)

**Comment by PPatrick-GitHub** [comment]
10:49:03.193/E: Wrapped CvException [org.opencv.core.CvException: cv::Exception: OpenCV(3.4.3) /build/3_4_pack-android/opencv/modules/core/src/matrix.cpp:367: error: (-215:Assertion failed) u != 0 in function 'void cv::Mat::create(int, const int*, int)'
] (file:///android_asset/modules/__images__.js#430)
Wrapped CvException [org.opencv.core.CvException: cv::Exception: OpenCV(3.4.3) /build/3_4_pack-android/opencv/modules/core/src/matrix.cpp:367: error: (-215:Assertion failed) u != 0 in function 'void cv::Mat::create(int, const int*, int)'
]
    at file:///android_asset/modules/__images__.js:430:0
    at file:/storage/emulated/0/脚本/Auto.js_Projects-1.9.14/Modules/EXT_IMAGES.js:68:0
    at _chkByImgTpl (/storage/emulated/0/脚本/Auto.js_Projects-1.9.14/Ant_Forest_Launcher.js:4925:0)
    at /storage/emulated/0/脚本/Auto.js_Projects-1.9.14/Ant_Forest_Launcher.js:4840:0
    at _getTar (/storage/emulated/0/脚本/Auto.js_Projects-1.9.14/Ant_Forest_Launcher.js:4958:0)
    at _scan (/storage/emulated/0/脚本/Auto.js_Projects-1.9.14/Ant_Forest_Launcher.js:4872:0)
    at /storage/emulated/0/脚本/Auto.js_Projects-1.9.14/Ant_Forest_Launcher.js:4796:0
    at /storage/emulated/0/脚本/Auto.js_Projects-1.9.14/Ant_Forest_Launcher.js:4130:0
    at /storage/emulated/0/脚本/Auto.js_Projects-1.9.14/Ant_Forest_Launcher.js:7005:0

**Comment by akatsukily** [comment]
同样的错误，不过我的重启也不行

**Comment by SuperMonster003** [comment]
https://github.com/SuperMonster003/Auto.js_Projects/issues/257#issuecomment-591798783
