### ISSUE TITLE
Bug反馈: 进入好友排行榜后出错

### ISSUE THREAD

**Issue by mybbcat** [SuperMonster003/Auto.js_Projects#264]
**问题描述**
28号开始出现进入好友排行榜后报错
之前可以正常收取能量

**日志截图**
01:08:27.511/E: Error: out of region: region = [972,0,108,2340], image.size = [2340,1080] (file:///android_asset/modules/__images__.js#523)
Error: out of region: region = [972,0,108,2340], image.size = [2340,1080]
    at buildRegion (file:///android_asset/modules/__images__.js:523:0)
    at file:///android_asset/modules/__images__.js:395:0
    at _check (/storage/emulated/0/脚本/Auto.js_Projects-master/Auto.js_Projects-master/Ant_Forest_Launcher.js:4907:0)
    at _chkByMultCol (/storage/emulated/0/脚本/Auto.js_Projects-master/Auto.js_Projects-master/Ant_Forest_Launcher.js:4888:0)
    at /storage/emulated/0/脚本/Auto.js_Projects-master/Auto.js_Projects-master/Ant_Forest_Launcher.js:4856:0
    at _getTar (/storage/emulated/0/脚本/Auto.js_Projects-master/Auto.js_Projects-master/Ant_Forest_Launcher.js:4958:0)
    at _scan (/storage/emulated/0/脚本/Auto.js_Projects-master/Auto.js_Projects-master/Ant_Forest_Launcher.js:4872:0)
    at /storage/emulated/0/脚本/Auto.js_Projects-master/Auto.js_Projects-master/Ant_Forest_Launcher.js:4796:0
    at /storage/emulated/0/脚本/Auto.js_Projects-master/Auto.js_Projects-master/Ant_Forest_Launcher.js:4130:0
    at /storage/emulated/0/脚本/Auto.js_Projects-master/Auto.js_Projects-master/Ant_Forest_Launcher.js:7005:0

**软件硬件信息**
操作系统: [ 安卓9]
设备型号: [小米9 pro]
Auto.js版本: [: 4.1.1 Alpha2]

**Comment by PPatrick-GitHub** [comment]
我也是这个问题，很久了的，需要重启手机才能好，然后过不了多久就又不行了

**Comment by AdAstracool** [comment]
同
