### ISSUE TITLE
碰到好友能量罩时

### ISSUE THREAD

**Issue by 17839170745** [SuperMonster003/Auto.js_Projects#40]
/E: Cannot convert NaN to java.lang.Integer (/storage/emulated/0/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js#1286)
Cannot convert NaN to java.lang.Integer
    at saveFriendNameImgBytesIfNeeded (/storage/emulated/0/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js:1286:0)
    at backToHeroList (/storage/emulated/0/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js:1262:0)
    at checkFriendsEnergy (/storage/emulated/0/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js:609:0)
    at checkEnergy (/storage/emulated/0/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js:454:0)
    at antForest (/storage/emulated/0/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js:60:0)
    at /storage/emulated/0/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js:52:0

**Comment by guohuatai** [comment]
是的，碰到好友能量保护罩会异常报错，中断运行

**Comment by SuperMonster003** [comment]
@guohuatai @17839170745 @luchangharry 
大家的反馈全部收到 我尽量在明天 (不迟于周一晚) 修复这些问题

**Comment by SuperMonster003** [comment]
已于 `v1.6.25 Alpha3` - `2019/05/26` 尝试修复此问题
