### ISSUE TITLE
问题反馈 TypeError: "put" value can't be undefined 

### ISSUE THREAD

**Issue by DanielEcho** [SuperMonster003/Auto.js_Projects#53]
```
22:25:39.812/E: TypeError: "put" value can't be undefined (file:/storage/emulated/0/脚本/Modules/MODULE_STORAGE.js#42)
TypeError: "put" value can't be undefined
    at put (file:/storage/emulated/0/脚本/Modules/MODULE_STORAGE.js:42:0)
    at saveIconBytesToTmp (/storage/emulated/0/脚本/Ant_Forest_Launcher.js:1394:0)
    at saveImgClipsBytesIfNeeded (/storage/emulated/0/脚本/Ant_Forest_Launcher.js:1361:0)
    at backToHeroList (/storage/emulated/0/脚本/Ant_Forest_Launcher.js:1338:0)
    at checkFriendsEnergy (/storage/emulated/0/脚本/Ant_Forest_Launcher.js:618:0)
    at checkEnergy (/storage/emulated/0/脚本/Ant_Forest_Launcher.js:458:0)
    at antForest (/storage/emulated/0/脚本/Ant_Forest_Launcher.js:59:0)
    at /storage/emulated/0/脚本/Ant_Forest_Launcher.js:51:0

```
![image](https://user-images.githubusercontent.com/29098657/59160199-1b900a00-8b06-11e9-949a-a7aed6197eb7.png)
autojs版本4.1.1 alpha2
Android 9

**Comment by DanielEcho** [comment]
v1.6.25 Alpha15已修复该问题
