### ISSUE TITLE
最新版2.3.1无法使用，提示 错误 translation has been interrupted

### ISSUE THREAD

**Issue by zhangfan156** [SuperMonster003/Auto.js_Projects#587]

**Comment by MrXIAGAO** [comment]
俺也一样

**Comment by huanglihang888** [comment]
已解决：ADB工具连接手机，执行SHell指令：adb shell pm grant org.autojs.autojs6 android.permission.WRITE_SECURE_SETTINGS

**Comment by MrXIAGAO** [comment]
> 
执行后报错😢
Exception occurred while executing 'grant':
java.lang.SecurityException: grantRuntimePermission: Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.
	at android.app.ContextImpl.enforce(ContextImpl.java:2250)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2278)
	at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermissionInternal(PermissionManagerServiceImpl.java:1367)
	at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermission(PermissionManagerServiceImpl.java:1349)
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:573)
	at android.permission.PermissionManager.grantRuntimePermission(PermissionManager.java:597)
	at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2565)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:292)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:6229)
	at android.os.Binder.shellCommand(Binder.java:1054)
	at android.os.Binder.onTransact(Binder.java:882)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4313)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:6213)
	at android.os.Binder.execTransactInternal(Binder.java:1290)
	at android.os.Binder.execTransact(Binder.java:1249)
