### ISSUE TITLE
小米手机6，排行榜列表参照值异常，脚本无法继续

### ISSUE THREAD

**Issue by c939984606** [SuperMonster003/Auto.js_Projects#66]

**Comment by c939984606** [comment]
17:25:54.451/E: Error: Error thrown on purpose (file:/storage/emulated/0/脚本/蚂蚁森林/Auto.js_Projects-master/Auto.js_Projects-master/Modules/MODULE_MONSTER_FUNC.js#846)
Error: Error thrown on purpose
    at messageAction (file:/storage/emulated/0/脚本/蚂蚁森林/Auto.js_Projects-master/Auto.js_Projects-master/Modules/MODULE_MONSTER_FUNC.js:846:0)
    at swipeUp (/storage/emulated/0/脚本/蚂蚁森林/Auto.js_Projects-master/Auto.js_Projects-master/Ant_Forest_Launcher.js:1607:0)
    at checkFriendsEnergy (/storage/emulated/0/脚本/蚂蚁森林/Auto.js_Projects-master/Auto.js_Projects-master/Ant_Forest_Launcher.js:767:0)
    at checkEnergy (/storage/emulated/0/脚本/蚂蚁森林/Auto.js_Projects-master/Auto.js_Projects-master/Ant_Forest_Launcher.js:522:0)
    at /storage/emulated/0/脚本/蚂蚁森林/Auto.js_Projects-master/Auto.js_Projects-master/Ant_Forest_Launcher.js:69:0
    at antForest (/storage/emulated/0/脚本/蚂蚁森林/Auto.js_Projects-master/Auto.js_Projects-master/Ant_Forest_Launcher.js:87:0)

**Comment by c939984606** [comment]
上个版本1.8.1没问题

**Comment by SuperMonster003** [comment]
已检查代码 未发现与上述功能相关的可能导致功能异常的改动 如新版再次失败 可尝试使用"图像识别"策略
