### ISSUE TITLE
小米9一直不停跳无障碍

### ISSUE THREAD

**Issue by zhongjun96** [SuperMonster003/Auto.js_Projects#69]
尝试过重启手机和重装app，问题依旧。运行设置空白。运行收能量就跳无障碍。
```
10:47:02.974/E: Wrapped com.stardust.autojs.runtime.exception.ScriptException: 无障碍服务已启用但并未运行，这可能是安卓的BUG，您可能需要重启手机或重启无障碍服务 (file:///android_asset/modules/__automator__.js#122)
Wrapped com.stardust.autojs.runtime.exception.ScriptException: 无障碍服务已启用但并未运行，这可能是安卓的BUG，您可能需要重启手机或重启无障碍服务
    at file:///android_asset/modules/__automator__.js:122:0
    at /storage/emulated/0/脚本/Auto.js_Projects-Ant_Forest/Ant_Forest_Launcher.js:41:0
```

**Comment by SuperMonster003** [comment]
此问题我无法通过代码解决 感谢支持
