### ISSUE TITLE
运行过程中会自动报错

### ISSUE THREAD

**Issue by jsedifier** [SuperMonster003/Auto.js_Projects#95]
大侠真的太厉害了，这脚本实在太牛了，不过使用过程中我还碰到了两个小问题，反馈一下：
1.帮收能量球的颜色默认收取的颜色有误，应和正常收取时一样
2.运行大概10分钟左右，我的小米6会有错误出现代码如下08:49:32.702/E: Wrapped CvException [org.opencv.core.CvException: /build/2_4_pack-android/opencv/modules/core/src/alloc.cpp:52: error: (-4) Failed to allocate 8294404 bytes in function void* cv::OutOfMemoryError(size_t)
] (file:///android_asset/modules/__images__.js#418)
Wrapped CvException [org.opencv.core.CvException: /build/2_4_pack-android/opencv/modules/core/src/alloc.cpp:52: error: (-4) Failed to allocate 8294404 bytes in function void* cv::OutOfMemoryError(size_t)
]
    at file:///android_asset/modules/__images__.js:418:0
    at checkRankListBottomTemplate (/storage/emulated/0/脚本/自动收能量/Ant_Forest_Launcher.js:1833:0)
    at swipeUp (/storage/emulated/0/脚本/自动收能量/Ant_Forest_Launcher.js:1710:0)
    at checkFriendsEnergy (/storage/emulated/0/脚本/自动收能量/Ant_Forest_Launcher.js:774:0)
    at checkEnergy (/storage/emulated/0/脚本/自动收能量/Ant_Forest_Launcher.js:523:0)
    at /storage/emulated/0/脚本/自动收能量/Ant_Forest_Launcher.js:75:0
    at antForest (/storage/emulated/0/脚本/自动收能量/Ant_Forest_Launcher.js:99:0)
    at /storage/emulated/0/脚本/自动收能量/Ant_Forest_Launcher.js:66:0

**Comment by SuperMonster003** [comment]
第二个oom的问题将在下一版尝试优化 避免内存溢出
第一个问题我没看明白 橙色的色值是为了匹配橙色能量球 从而可以识别并点击

**Comment by jsedifier** [comment]
不知回复的邮件有没有收到，橙色色标是对的，但是能量球的颜色其实还是和普通能量球一样的颜色，只是能量球下面多了一个橙色标记

**Comment by SuperMonster003** [comment]
橙色球其实就是识别的下面橙色的部分 点击此部分即可收取橙色球 橙色球的识别目前只能想到用颜色匹配橙色部分的方法  
我还是没太明白你的疑问或需求是什么
